### ISSUE TITLE
HDR images from iPhones error with LoadImage module

### ISSUE THREAD

**Issue by fofr** [fofr/cog-face-to-many#1]
```
Running workflow
got prompt
Executing node 22, title: Load Image, class type: LoadImage
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "/src/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/src/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/src/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/src/ComfyUI/nodes.py", line 1493, in load_image
i = ImageOps.exif_transpose(i)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/PIL/ImageOps.py", line 617, in exif_transpose
image.load()
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/PIL/ImageFile.py", line 288, in load
raise OSError(msg)
OSError: image file is truncated (0 bytes not processed)
```

This is a bug in ComfyUI:
https://github.com/comfyanonymous/ComfyUI/issues/2692

**Comment by fofr** [comment]
<img width="703" alt="Screenshot 2024-03-07 at 14 07 56" src="https://github.com/fofr/cog-face-to-many/assets/319055/56d57b06-33ba-45f7-a533-b7b9cba4b625">

**Comment by fofr** [comment]
The HDR image is now fixed by converting the jpeg to a simple png.
