### ISSUE TITLE
Error Retrieving Information for 'Simple Eval Examples' Node: FileNotFoundError

### ISSUE THREAD

**Issue by vreabernardo** [fofr/cog-face-to-many#16]
Upon executing main.py with python main.py --listen 0.0.0.0, this error occurs:

```
[ERROR] An error occurred while retrieving information for the 'Simple Eval Examples' node.
Traceback (most recent call last):
  File "/src/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/src/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/src/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 4357, in INPUT_TYPES
    with open(filepath, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/src/ComfyUI/custom_nodes/efficiency-nodes-comfyui/workflows/SimpleEval_Node_Examples.txt'
```

**Comment by fofr** [comment]
Have you install the custom nodes by running scripts/clone_plugins.sh?

**Comment by vreabernardo** [comment]
yes I did.
<img width="503" alt="Screenshot 2024-03-22 at 19 54 43" src="https://github.com/fofr/cog-face-to-many/assets/45080358/394ccc76-ce4d-4aa1-b72d-dd1f22cca109">
