### ISSUE TITLE
KeyError: 'Efficient Loader'

### ISSUE THREAD

**Issue by wytxer** [fofr/cog-face-to-many#49]
Thank you to the author for the great contribution to this project!

I am a beginner in Python, and I wanted to customize and deploy this project, so I downloaded it locally using macOS. However, I encountered the following error when deploying it to Replicate using cog:

```log
Random seed set to: 2805624572
Checking inputs
✅ /tmp/inputs/input.png
====================================
Running workflow
got prompt
Error handling request
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "/src/ComfyUI/server.py", line 41, in cache_control
response: web.Response = await handler(request)
File "/src/ComfyUI/server.py", line 468, in post_prompt
valid = execution.validate_prompt(prompt)
File "/src/ComfyUI/execution.py", line 624, in validate_prompt
class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'Efficient Loader'
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 259, in predict
self.comfyUI.run_workflow(wf)
File "/src/helpers/comfyui.py", line 233, in run_workflow
prompt_id = self.queue_prompt(workflow)
File "/src/helpers/comfyui.py", line 174, in queue_prompt
raise Exception(
Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.
ComfyUI error: 500 Internal Server Error
```

Here are the steps I executed:

```bash
git clone --recurse-submodules https://github.com/fofr/cog-face-to-many.git && cd cog-face-to-many/ComfyUI

cog push r8.im/username/face-to-many
```

Here is the complete startup log, no errors are seen, and it seems that the custom nodes were not loaded.
[setup-logs.txt](https://github.com/user-attachments/files/15804054/setup-logs.txt)

What went wrong? Looking forward to your reply.

**Comment by wytxer** [comment]
@fofr Could you please take a look at this issue when you have time? Thank you very much!

**Comment by Citramones** [comment]
> Thank you to the author for the great contribution to this project!
> 
> I am a beginner in Python, and I wanted to customize and deploy this project, so I downloaded it locally using macOS. However, I encountered the following error when deploying it to Replicate using cog:
> 
> ```
> Random seed set to: 2805624572
> Checking inputs
> ✅ /tmp/inputs/input.png
> ====================================
> Running workflow
> got prompt
> Error handling request
> Traceback (most recent call last):
> File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
> resp = await request_handler(request)
> File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
> resp = await handler(request)
> File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
> return await handler(request)
> File "/src/ComfyUI/server.py", line 41, in cache_control
> response: web.Response = await handler(request)
> File "/src/ComfyUI/server.py", line 468, in post_prompt
> valid = execution.validate_prompt(prompt)
> File "/src/ComfyUI/execution.py", line 624, in validate_prompt
> class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
> KeyError: 'Efficient Loader'
> Traceback (most recent call last):
> File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
> result = predict(**payload)
> File "/src/predict.py", line 259, in predict
> self.comfyUI.run_workflow(wf)
> File "/src/helpers/comfyui.py", line 233, in run_workflow
> prompt_id = self.queue_prompt(workflow)
> File "/src/helpers/comfyui.py", line 174, in queue_prompt
> raise Exception(
> Exception: ComfyUI Error – Your workflow could not be run. This usually happens if you’re trying to use an unsupported node. Check the logs for 'KeyError: ' details, and go to https://github.com/fofr/cog-comfyui to see the list of supported custom nodes.
> ComfyUI error: 500 Internal Server Error
> ```
> 
> Here are the steps I executed:
> 
> ```shell
> git clone --recurse-submodules https://github.com/fofr/cog-face-to-many.git && cd cog-face-to-many/ComfyUI
> 
> cog push r8.im/username/face-to-many
> ```
> 
> Here is the complete startup log, no errors are seen, and it seems that the custom nodes were not loaded. [setup-logs.txt](https://github.com/user-attachments/files/15804054/setup-logs.txt)
> 
> What went wrong? Looking forward to your reply.

Did you manage to solve the problem and deploy it?

**Comment by wytxer** [comment]
Unresolved, I used ChatGPT for coding assistance, tried modifying many versions, but all resulted in errors. Have you encountered the same issue? @Citramones

**Comment by Citramones** [comment]
> Unresolved, I used ChatGPT for coding assistance, tried modifying many versions, but all resulted in errors. Have you encountered the same issue? @Citramones

 I have the same error. The only thing that worked for me was using basic nodes and creating an image from text.

**Comment by wytxer** [comment]
I didn't understand. Specifically, which parts of the code did you modify to successfully deploy? Could you share it? @Citramones

**Comment by tzktok** [comment]
download the efficient loder node from https://github.com/jags111/efficiency-nodes-comfyui.git here..Load this in custom_nodes  folder @wytxer @Citramones ..

**Comment by wytxer** [comment]
Thanks, I'll try it @tzktok

**Comment by Citramones** [comment]
I need to git clone https://github.com/jags111/efficiency-nodes-comfyui and move it to custom_nodes folder? @tzktok

**Comment by tzktok** [comment]
> I need to git clone https://github.com/jags111/efficiency-nodes-comfyui and move it to custom_nodes folder? @tzktok

yup.. @Citramones
